class GeneratorManager {
    constructor() {
    }

    generate(containerId, text) {
        const container = document.getElementById(containerId);
        if (!container) return;

        container.innerHTML = ''; // Clear

        if (!text) return;

        try {
            new QRCode(container, {
                text: text,
                width: 256,
                height: 256,
                colorDark : "#000000",
                colorLight : "#ffffff",
                correctLevel : QRCode.CorrectLevel.H
            });
        } catch (e) {
            console.error("QR Generation failed", e);
            container.innerText = "Error generating QR";
        }
    }

    download(containerId, filename = "qrcode.png") {
        const container = document.getElementById(containerId);
        if (!container) return;

        // Try to find the image generated by QRCode.js
        // It often replaces canvas with img, or keeps canvas
        const img = container.querySelector("img");

        if (img && img.src && img.src.startsWith('data:image')) {
            this._triggerDownload(img.src, filename);
            return;
        }

        const canvas = container.querySelector("canvas");
        if (canvas) {
            const dataUrl = canvas.toDataURL("image/png");
            this._triggerDownload(dataUrl, filename);
            return;
        }

        alert("No QR code available to download. Please generate one first.");
    }

    _triggerDownload(url, filename) {
        const a = document.createElement("a");
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
    }
}
